name: Deploy para Azure Web App - EC-Crypto-Pro

on:
  push:
    branches:
      - main  # ou 'master', dependendo do nome do seu branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: EC-Crypto-Pro
          slot-name: Production
          package: .
